version: "3.9"

services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "5100:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  celery:
    build: .
    command: celery -A app.task worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/usr/src/app